name: Jingtin Tim Lin
favicon: null
layout_spectrum: 0.4945329325273633
typography_spectrum: 0.48839205340482295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7728108584415168
  lightness: 0.6576193091459572
  saturation: 0.8854255769401789
  rhythmicContrast: 0.33511704998090863
purpose: []
